# TensorFlow Basics

In [1]:
import tensorflow as tf

AttributeError: module 'tensorboard' has no attribute 'lazy'

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.3.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computations **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [15]:
sess.close()

## Operations

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [23]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.1066899  -0.67079175 -0.17030844 -0.94966197]
 [ 0.36453074  0.07695128  0.75996757  0.26596269]
 [ 0.09675932  0.0172567   0.61638004 -0.55172282]
 [ 0.02814705 -0.61808312 -0.35328296  0.08349258]]


[[ 0.68672144  0.84300661  0.01917613  0.15367568]
 [ 0.8822968   0.6406256   0.11968935  0.34425914]
 [ 0.32183003  0.31339324  0.0376581   0.34806168]
 [ 0.00820863  0.74296677  0.67269909  0.48290253]]




## Matrix Multiplication

In [58]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [59]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [60]:
b = tf.constant([[10],[100]])

In [61]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [62]:
result = tf.matmul(a,b)

In [63]:
result.eval()

array([[210],
       [430]])